### PR TITLE
In out beh

### PR DESCRIPTION
**Pull request by d-robles**
I am not sure if you can see the changes. 

line 39 

prop_correct = zeros(nsubs,length(new_cond));
prop_correctRej = zeros(nsubs,length(new_cond));
medianRT_correct = zeros(nsubs,length(new_cond));
medianRT_falseAlarm = zeros(nsubs,length(new_cond));

line 162 

     %reassign conditions for facing in vs out
        if is_goofy(i_sub)
            if strcmp(conds{i_cond},'P_CCW') || strcmp(conds{i_cond},'NP_CW')
                new_cond_index = 1;
            else
                new_cond_index = 2;
            end
        elseif ~is_goofy(i_sub)
            if strcmp(conds{i_cond},'P_CCW') || strcmp(conds{i_cond},'NP_CW')
                new_cond_index = 2;
            else
                new_cond_index = 1;
            end
        end

        prop_correct(i_sub,new_cond_index) = count_correct / count_targets;
        prop_correctRej(i_sub,new_cond_index) = count_correctRej / count_standards;
        medianRT_correct(i_sub,new_cond_index) = median(RT_correct);
        medianRT_falseAlarm(i_sub,new_cond_index) = median(RT_falseAlarm);

### CODE REVIEW

**Comment by kylemath** [comment]
yup that looks good to me, i thought of that is_goofy(i_sub) in the shower this morning but forgot before I could text you
Good work

**Review by kylemath — COMMENTED** [review]
Great

**Comment by kylemath** [comment]
yup just reviewed and merged the pull request.
Does it run?

**Comment by d-robles** [comment]
It does

**Comment by kylemath** [comment]
yes saw that on slack
good work

**Pull request merged**
